# Generated by Django 4.1.1 on 2022-09-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="currency",
            field=models.CharField(
                choices=[("won", "원"), ("usd", "USD")], max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "남"), ("female", "여")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("kr", "한국어"), ("en", "English")], max_length=2
            ),
        ),
    ]
