# Generated by Django 4.1.1 on 2022-09-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0005_room_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "편의시설"},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name_plural": "숙소"},
        ),
        migrations.AlterField(
            model_name="room",
            name="city",
            field=models.CharField(default="서울", max_length=80),
        ),
        migrations.AlterField(
            model_name="room",
            name="country",
            field=models.CharField(default="대한민국", max_length=50),
        ),
        migrations.AlterField(
            model_name="room",
            name="kind",
            field=models.CharField(
                choices=[
                    ("entire_place", "전체 공간"),
                    ("private_room", "개인실"),
                    ("shared_room", "공유 공간"),
                ],
                max_length=20,
            ),
        ),
    ]
