# Generated by Django 4.1.1 on 2022-09-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0002_experience_categories_alter_perk_details_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experience",
            options={"verbose_name_plural": "활동"},
        ),
        migrations.AlterModelOptions(
            name="perk",
            options={"verbose_name_plural": "체험"},
        ),
        migrations.AlterField(
            model_name="experience",
            name="city",
            field=models.CharField(default="서울", max_length=80),
        ),
        migrations.AlterField(
            model_name="experience",
            name="country",
            field=models.CharField(default="대한민국", max_length=50),
        ),
    ]
