# Generated by Django 4.1.1 on 2022-09-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_alter_review_experience_alter_review_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="payload",
            field=models.TextField(default=""),
        ),
    ]
