# Generated by Django 4.1.1 on 2022-09-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_review_payload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="payload",
            field=models.TextField(default="", max_length=3000),
        ),
    ]
