# Generated by Django 4.1.1 on 2022-09-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("direct_messages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chattingroom",
            options={"verbose_name_plural": "채팅방"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name_plural": "DM"},
        ),
        migrations.AddField(
            model_name="chattingroom",
            name="name",
            field=models.CharField(default="이름없는 채팅방", max_length=15),
        ),
    ]
