# Generated by Django 4.1.1 on 2022-09-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"verbose_name_plural": "예약"},
        ),
        migrations.AddField(
            model_name="booking",
            name="experience_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="guests",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
